#####################################
#                                   #
#            TeeOlympics            #
#                                   #
#####################################

motd:
  line1: "&8Serveur des &6&lTeeOlympics"
  line2: "&a&o3ème éditions"

slot: 20