name: '${project.artifactId}'
version: '${project.version}'
main: '${project.groupId}.${project.artifactId}'
api-version: '1.20'
authors: [KIZAFOX]
contributors: [Pipou, Nehr]
description: '${project.description}'
website: '${project.url}'