name: CD
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: APT UPDATE and INSTALL SSHPASS
        run:
          sudo apt update && sudo apt install sshpass

      - name: Deploy TeeOlympics Plugin
        run:
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd /home/MinecraftServers/main/plugins/ && sudo rm TeeOlympics-1.0-SNAPSHOT.jar && sudo wget https://github.com/KIZAFOX/TeeOlympics-Minecraft/raw/main/target/TeeOlympics-1.0-SNAPSHOT.jar"